dir:
    data: 'data/antenna'
    model: 'models/antenna'

vars: ['l1', 'l2', 'l3', 'l4']
cell_lengths: [0.4e-3, 0.4e-3, 0.262e-3]
cfl_number: 0.9
air_buffers: [3, 3, 3]
seq_len: 25
train_ratio: 0.2
field_target: 'ezhxhy' # ez | hx | hy | ezhxhy | ... any other combinations
ph_factor: 0.01 # you can set this to a value like 0.1 or 0.2 for phase factor
epoch_to_validate: 10
sample_dt: 10 # sample every 10 timesteps

model:
    name: 'SimI2V'
    in_channels: 1
    out_channels: 12
    dim: 64
    hidden_channels: [32, 64, 64, 64, 32]
    groups: 3
    seq_len: 25
    